<?php

module_load_include('inc', 'entity_toolbox_example', 'entity_toolbox_example.info');

/**
 * Implements hook_entity_info().
 */
function entity_toolbox_example_entity_info() {
  $info = array();
  $info += hook_build('entity_info', 'example');
  $info += hook_build('entity_info', 'example_type');

  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function entity_toolbox_example_entity_property_info() {
  $info = array();
  $info += hook_build('entity_property_info', 'example');
  $info += hook_build('entity_property_info', 'example_type');

  return $info;
}

/**
 * Implements hook_permission().
 */
function entity_toolbox_example_permission() {
  $permissions = array();
  $permissions += hook_build('permission', 'example');
  $permissions += hook_build('permission', 'example_type');

  return $permissions;
}