<?php

module_load_include('inc', 'entity_toolbox_example', 'entity_toolbox_example.info');
module_load_include('inc', 'entity_toolbox_example', 'entity_toolbox_example.functions');

///**
// * Implements hook_menu().
// */
//function entity_toolbox_example_menu() {
//  $items = array();
//  $items += menu_build('entity_toolbox_example');
//
//  return $items;
//}

///**
// * Implements hook_entity_property_info().
// */
//function entity_toolbox_example_entity_property_info() {
//  $info = array();
//  $info += entity_property_info_build('foo');
//  $info += entity_property_info_build('foo_type');
//
//  return $info;
//}

///**
// * Implements hook_entity_operation_info().
// */
//function entity_toolbox_example_entity_operation_info() {
//  $info = array();
//  $info += entity_operation_info_build('foo');
//  $info += entity_operation_info_build('foo_type');
//
//  return $info;
//}

///**
// * Implements hook_permission().
// */
//function entity_toolbox_example_permission() {
//  $permissions = array();
//  $permissions += permissions_build('foo');
//  $permissions += permissions_build('foo_type');
//
//  return $permissions;
//}
//
///**
// * Implements hook_theme().
// */
//function entity_toolbox_example_theme($existing, $type, $theme, $path) {
//  $themes = array();
//  $themes += theme_build('entity_toolbox_example');
//
//  return $themes;
//}