<?php

/**
 * @file
 *
 * This file contains functions to extract data from built info.
 */

/**
 * Extracts the schemas names for an entity type.
 *
 * @param string $entity_type
 *   The entity type.
 * @param array  $toolbox_info
 *   The toolbox info to extract the schemas from.
 *
 * @return string[]
 */
function toolbox_info_extract_schemas($entity_type, $toolbox_info = array()) {
}

/**
 * Extract the "base schema" fields.
 *
 * @param string $entity_type
 *   The entity type name.
 * @param string $schema_type
 *   The schema type, defaults "base".
 *
 * @return array
 */
function toolbox_info_extract_schema_fields($entity_type, $schema_type = 'base') {
}